version: '3'

services:
  app:
    build: ./src
    container_name: flask_app
    environment:
      - DB_URL=postgresql://user:password@db:5432/containers
    command: tail -f /dev/null
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: db
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    ports:
      - 5405:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=containers