version: '3'

services:
  app:
    build: ./WebService
    container_name: flask_app
    environment:
      - DB_URL=postgresql://user:password@db:5432/containers
    command: python app/main.py
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password 
      - POSTGRES_DB=containers